# Site settings
title: Les zinzins
email: contact@leszinzins.co
description: "Site collaboratif sur l'activité évènementielle du grand Toulouse"
baseurl: ""
url: "http://leszinzins.co"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
- bower_components
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
- bower.json